services:
  db:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_DB: csci602db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data
volumes:
  pgdata:
